SIMPLYE-257 settings page
NatLibFi/ekirjasto-android-core pull request #44
Opened 2024-04-12 12:44 UTC by mikko-work

**What's this do?**
Created a new fragment to replace the settings page. UI style for buttons is not there yet, but I think that can be separate PR, since would require to be done in the theme library anyway. This replaces the earlier PR for passkey auth, since I based this branch on that.

**Why are we doing this? (w/ JIRA link if applicable)**
[Quick blurb about why the code is needed and Jira link goes here / Do these changes meet the business requirements of the story?]

**How should this be tested? / Do these changes have associated tests?**
[Description of any tests that need to be performed once merged goes here]

**Dependencies for merging? Releasing to production?**
[Description of any watchouts, dependencies, or issues we should be aware of goes here]

**Have you updated the changelog?**

**Has the application documentation been updated for these changes?**

**Did someone actually run this code to verify it works?**

2024-04-12 12:59 UTC, sylvain-degeilh-lingsoft requested changes

2024-04-12 12:59 UTC, sylvain-degeilh-lingsoft commented on simplified-ui-accounts/src/main/res/values/strings.xml
> +  <string name="account_login_suomifi">Login with Suomi.FI</string>
https://jira.lingsoft.fi/browse/SIMPLYE-310

2024-04-12 12:59 UTC, sylvain-degeilh-lingsoft commented on simplified-ui-accounts/src/main/res/values/strings.xml
> +  <string name="account_login_passkey">Login with Passkey</string>
https://jira.lingsoft.fi/browse/SIMPLYE-311

2024-04-15 11:06 UTC, mikko-work commented
Updated with fixed to 302, 310, 311.

2024-04-15 12:43 UTC, sylvain-degeilh-lingsoft approved these changes

2024-04-15 12:44 UTC, merged